services:
  - type: web
    name: SABAN-V1
    env: node
    branch: main
    repo: https://github.com/sataniceypz/Izumi-v3.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: True
    envVars:
      - key: SESSION_ID
        sync: false
      - key: DATABASE_URL
        sync: false
